name: "godot-ci export"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: GW2CurrencyItemDisplay
  PROJECT_PATH: .

jobs:
  build:
    name: Godot Build
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-4.3
    steps:
      - name: Get version
        run: |
          SUBSTRING=$(echo "${GITHUB_REF#refs/tags/}" | cut -c 2-)
          echo "TAG_VERSION=$SUBSTRING" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Setup
        run: |
          mkdir -v -p builds/windows builds/linux ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build Windows
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Build Linux
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: builds/windows
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: builds/linux
